const express=require('express');const fs=require('fs');const path=require('path');const crypto=require('crypto');
const app=express(),PORT=process.env.PORT||8080,DATA=path.join(__dirname,'data.json');
const collections=['customers','products','suppliers','purchases','invoices','payments','expenses','appointments','followups','activity'];
const baseSettings={shopName:'SHAM MOBILE ZONE AND ACCESSOREIS',phone:'',whatsapp:'',address:'',currency:'Rs.',tax:0,logo:''};
const initial={shops:[],settingsByShop:{},users:[],customers:[],products:[],suppliers:[],purchases:[],invoices:[],payments:[],expenses:[],appointments:[],followups:[],activity:[]};
function clone(x){return JSON.parse(JSON.stringify(x))}function read(){if(!fs.existsSync(DATA))write(initial);try{let d=JSON.parse(fs.readFileSync(DATA,'utf8'));for(const k of Object.keys(initial))if(!(k in d))d[k]=clone(initial[k]);return d}catch(e){return clone(initial)}}function write(d){fs.writeFileSync(DATA,JSON.stringify(d,null,2))}
function id(p){return p+'-'+Date.now().toString(36).toUpperCase()+'-'+crypto.randomBytes(3).toString('hex')}
function hash(p,s=crypto.randomBytes(16).toString('hex')){return {salt:s,hash:crypto.scryptSync(p,s,64).toString('hex')}}function verify(p,u){try{return crypto.timingSafeEqual(Buffer.from(crypto.scryptSync(p,u.salt,64).toString('hex'),'hex'),Buffer.from(u.hash,'hex'))}catch{return false}}
let d=read();
// First-run/migration: create a default shop and move existing records into it.
if(!d.shops.length){let shopId=id('SHOP');d.shops.push({id:shopId,name:d.settings?.shopName||baseSettings.shopName,status:'active',createdAt:new Date().toISOString()});d.settingsByShop[shopId]={...baseSettings,...(d.settings||{})};for(const k of collections)if(Array.isArray(d[k]))d[k].forEach(x=>{x.shopId=shopId});let admin=d.users.find(u=>u.username==='admin');if(admin){admin.role='SuperAdmin';admin.shopId=null}else{let h=hash('admin123');admin={id:id('USR'),name:'Administrator',username:'admin',role:'SuperAdmin',permissions:['all'],shopId:null,...h,createdAt:new Date().toISOString()};d.users.push(admin)}write(d)}
// Ensure every existing user has a shopId except the super admin.
const firstShop=()=>read().shops[0]?.id;d=read();d.users.forEach(u=>{if(u.username==='admin'||u.role==='SuperAdmin'){u.role='SuperAdmin';u.shopId=null}else if(!u.shopId)u.shopId=firstShop()});write(d);
const sessions=new Map();
app.use(express.json({limit:'8mb'}));app.use(express.static(path.join(__dirname,'public')));
function auth(req,res,next){let token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');let sess=sessions.get(token);if(!sess)return res.status(401).json({error:'Please log in again'});let data=read(),u=data.users.find(x=>x.id===sess.userId);if(!u)return res.status(401).json({error:'User account not found'});req.user=u;req.token=token;req.shopId=u.role==='SuperAdmin'?(sess.shopId||null):u.shopId;req.data=data;next()}
function shopFor(req){let data=req.data||read();if(!req.shopId&&req.user?.role==='SuperAdmin')return null;return data.shops.find(x=>x.id===req.shopId)}
function scopedRows(data,name,shopId){return (data[name]||[]).filter(x=>x.shopId===shopId)}
function own(req,x){return req.user.role==='SuperAdmin'||x.shopId===req.shopId}
function safeUser(u){return {id:u.id,name:u.name,username:u.username,email:u.email||'',phone:u.phone||'',role:u.role,permissions:u.permissions||[],shopId:u.shopId||null}}
app.post('/api/login',(q,s)=>{let b=q.body||{},data=read(),u=data.users.find(x=>x.username?.toLowerCase()===String(b.username||'').trim().toLowerCase());if(!u||!verify(String(b.password||''),u))return s.status(401).json({error:'Invalid username or password'});let shop=u.shopId?data.shops.find(x=>x.id===u.shopId):data.shops[0];if(shop&&shop.status==='suspended')return s.status(403).json({error:'This business account is suspended'});let token=crypto.randomBytes(32).toString('hex');sessions.set(token,{userId:u.id,shopId:u.shopId||shop?.id||null});s.json({token,user:safeUser(u),shop:shop||null})});
app.post('/api/signup',(q,s)=>{let data=read(),b=q.body||{},name=String(b.name||'').trim(),businessName=String(b.businessName||'').trim(),username=String(b.username||'').trim(),email=String(b.email||'').trim(),phone=String(b.phone||'').trim(),password=String(b.password||'');if(!name||!businessName||!username||!email||!phone||password.length<6)return s.status(400).json({error:'Full name, business name, username, email, phone and a password of at least 6 characters are required'});if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return s.status(400).json({error:'Enter a valid email address'});if(data.users.some(u=>u.username.toLowerCase()===username.toLowerCase()))return s.status(400).json({error:'Username already exists'});if(data.users.some(u=>String(u.email||'').toLowerCase()===email.toLowerCase()))return s.status(400).json({error:'Email already registered'});if(data.shops.some(x=>x.name.toLowerCase()===businessName.toLowerCase()))return s.status(400).json({error:'Business name already registered'});let shopId=id('SHOP'),h=hash(password),u={id:id('USR'),name,username,email,phone,role:'Owner',permissions:['all'],shopId:shopId,...h,createdAt:new Date().toISOString()};data.shops.push({id:shopId,name:businessName,status:'active',ownerUserId:u.id,createdAt:new Date().toISOString()});data.settingsByShop[shopId]={...baseSettings,shopName:businessName,phone,whatsapp:phone};data.users.push(u);write(data);s.status(201).json({ok:true,message:'Business account created successfully. You can now log in.',user:safeUser(u),shop:data.shops.at(-1)})});
app.get('/api/me',auth,(q,s)=>{let shop=shopFor(q);s.json({user:safeUser(q.user),shop:shop||null})});
app.post('/api/logout',auth,(q,s)=>{sessions.delete(q.token);s.json({ok:true})});
app.post('/api/change-password',auth,(q,s)=>{let b=q.body||{},data=read(),u=data.users.find(x=>x.id===q.user.id);if(!verify(String(b.currentPassword||''),u))return s.status(401).json({error:'Current password is incorrect'});let np=String(b.newPassword||'');if(np.length<6)return s.status(400).json({error:'New password must be at least 6 characters'});if(np!==String(b.confirmPassword||''))return s.status(400).json({error:'New passwords do not match'});let h=hash(np);u.salt=h.salt;u.hash=h.hash;write(data);s.json({ok:true,message:'Password changed successfully'})});
app.get('/api/data',auth,(q,s)=>{let data=read(),shop=shopFor(q);if(!shop)return s.status(400).json({error:'Select a shop first'});let out={settings:data.settingsByShop[shop.id]||{...baseSettings,shopName:shop.name},shops:q.user.role==='SuperAdmin'?data.shops:undefined};for(const k of collections)out[k]=scopedRows(data,k,shop.id);s.json(out)});
app.post('/api/switch-shop/:id',auth,(q,s)=>{if(q.user.role!=='SuperAdmin')return s.status(403).json({error:'Only Super Admin can switch businesses'});let data=read(),shop=data.shops.find(x=>x.id===q.params.id);if(!shop)return s.status(404).json({error:'Shop not found'});let sess=sessions.get(q.token);sess.shopId=shop.id;s.json({ok:true,shop})});
app.get('/api/shops',auth,(q,s)=>{if(q.user.role!=='SuperAdmin')return s.status(403).json({error:'Super Admin only'});let data=read();s.json(data.shops.map(sh=>({...sh,owner:data.users.find(u=>u.id===sh.ownerUserId)?.name||'',users:data.users.filter(u=>u.shopId===sh.id).length,customers:data.customers.filter(x=>x.shopId===sh.id).length,invoices:data.invoices.filter(x=>x.shopId===sh.id).length})))});
app.put('/api/shops/:id',auth,(q,s)=>{if(q.user.role!=='SuperAdmin')return s.status(403).json({error:'Super Admin only'});let data=read(),sh=data.shops.find(x=>x.id===q.params.id);if(!sh)return s.status(404).json({error:'Shop not found'});if(q.body.name&&data.shops.some(x=>x.id!==sh.id&&x.name.toLowerCase()===String(q.body.name).trim().toLowerCase()))return s.status(400).json({error:'Business name already exists'});if(q.body.name){sh.name=String(q.body.name).trim();data.settingsByShop[sh.id]={...(data.settingsByShop[sh.id]||{}),shopName:sh.name}}if(q.body.status)sh.status=q.body.status;write(data);s.json(sh)});
function crud(name,prefix,required=[]){app.post('/api/'+name,auth,(q,s)=>{let data=read(),b=q.body||{},shop=shopFor(q);if(!shop)return s.status(400).json({error:'Select a shop first'});for(const k of required)if(!String(b[k]??'').trim())return s.status(400).json({error:k+' is required'});let x={...b,id:id(prefix),shopId:shop.id,createdAt:new Date().toISOString()};data[name].push(x);data.activity.push({id:id('ACT'),shopId:shop.id,action:'Created '+name.slice(0,-1),at:new Date().toISOString(),detail:x.id});write(data);s.status(201).json(x)});app.put('/api/'+name+'/:id',auth,(q,s)=>{let data=read(),x=data[name].find(v=>String(v.id)===String(q.params.id));if(!x||!own(q,x))return s.status(404).json({error:'Not found'});Object.assign(x,q.body||{},{updatedAt:new Date().toISOString()});write(data);s.json(x)});app.delete('/api/'+name+'/:id',auth,(q,s)=>{let data=read(),x=data[name].find(v=>String(v.id)===String(q.params.id));if(!x||!own(q,x))return s.status(404).json({error:'Not found'});data[name]=data[name].filter(v=>String(v.id)!==String(q.params.id));write(data);s.json({ok:true})})}
crud('products','PRD',['name']);crud('suppliers','SUP',['name']);crud('purchases','PUR',['supplierId','date']);crud('expenses','EXP',['category','amount','date']);crud('appointments','APT',['customerId','date']);crud('followups','FUP',['customerId','date']);
app.post('/api/customers',auth,(q,s)=>{let data=read(),shop=shopFor(q),b=q.body||{};if(!shop)return s.status(400).json({error:'Select a shop first'});if(!String(b.name||'').trim()||!String(b.phone||'').trim())return s.status(400).json({error:'Name and phone are required'});let nums=scopedRows(data,'customers',shop.id).map(c=>+(String(c.serial||'').match(/SHOP-(\d+)/)||[,0])[1]),n=Math.max(0,...nums)+1,x={...b,id:id('CUS'),shopId:shop.id,serial:'SHOP-'+String(n).padStart(4,'0'),createdAt:new Date().toISOString()};data.customers.push(x);write(data);s.status(201).json(x)});
app.post('/api/invoices',auth,(q,s)=>{let data=read(),shop=shopFor(q),b=q.body||{},items=Array.isArray(b.items)?b.items:[];if(!shop)return s.status(400).json({error:'Select a shop first'});if(!b.customerId||!items.length)return s.status(400).json({error:'Customer and at least one item are required'});let customer=data.customers.find(x=>x.id===b.customerId&&x.shopId===shop.id);if(!customer)return s.status(400).json({error:'Customer does not belong to this business'});let subtotal=items.reduce((a,i)=>a+Number(i.qty||1)*Number(i.price||0),0),discount=Number(b.discount||0),tax=Number(b.tax||0),total=Math.max(0,subtotal-discount+tax),paid=Math.min(total,Math.max(0,Number(b.paid||0))),num=data.invoices.filter(x=>x.shopId===shop.id).length+1,x={...b,id:id('INV'),shopId:shop.id,number:'INV-'+String(num).padStart(5,'0'),items,subtotal,discount,tax,total,paid,remaining:total-paid,status:paid>=total?'Paid':paid?'Partial':'Pending',createdAt:new Date().toISOString()};data.invoices.push(x);if(paid)data.payments.push({id:id('PAY'),shopId:shop.id,invoiceId:x.id,customerId:x.customerId,amount:paid,method:b.paymentMethod||'Cash',date:new Date().toISOString(),note:'Initial invoice payment'});write(data);s.status(201).json(x)});
app.put('/api/invoices/:id',auth,(q,s)=>{let data=read(),x=data.invoices.find(v=>String(v.id)===String(q.params.id));if(!x||!own(q,x))return s.status(404).json({error:'Not found'});Object.assign(x,q.body||{});x.total=Number(x.total||0);x.paid=Math.min(x.total,Math.max(0,Number(x.paid||0)));x.remaining=x.total-x.paid;x.status=x.paid>=x.total?'Paid':x.paid?'Partial':'Pending';write(data);s.json(x)});
app.delete('/api/invoices/:id',auth,(q,s)=>{let data=read(),x=data.invoices.find(v=>String(v.id)===String(q.params.id));if(!x||!own(q,x))return s.status(404).json({error:'Not found'});data.invoices=data.invoices.filter(v=>v.id!==x.id);data.payments=data.payments.filter(v=>v.invoiceId!==x.id||!own(q,v));write(data);s.json({ok:true})});
app.post('/api/payments',auth,(q,s)=>{let data=read(),shop=shopFor(q),b=q.body||{},inv=data.invoices.find(x=>x.id===b.invoiceId&&x.shopId===shop.id);if(!inv)return s.status(404).json({error:'Invoice not found'});let amount=Math.min(inv.remaining,Math.max(0,Number(b.amount||0)));if(!amount)return s.status(400).json({error:'Valid payment amount required'});let p={...b,id:id('PAY'),shopId:shop.id,amount,date:b.date||new Date().toISOString()};data.payments.push(p);inv.paid=Number(inv.paid||0)+amount;inv.remaining=Math.max(0,inv.total-inv.paid);inv.status=inv.paid>=inv.total?'Paid':inv.paid?'Partial':'Pending';write(data);s.status(201).json(p)});
app.delete('/api/payments/:id',auth,(q,s)=>{let data=read(),p=data.payments.find(x=>x.id===q.params.id);if(!p||!own(q,p))return s.status(404).json({error:'Not found'});let inv=data.invoices.find(x=>x.id===p.invoiceId);if(inv){inv.paid=Math.max(0,Number(inv.paid||0)-Number(p.amount||0));inv.remaining=Math.max(0,inv.total-inv.paid);inv.status=inv.paid>=inv.total?'Paid':inv.paid?'Partial':'Pending'}data.payments=data.payments.filter(x=>x.id!==p.id);write(data);s.json({ok:true})});
app.put('/api/settings',auth,(q,s)=>{let data=read(),shop=shopFor(q);if(!shop)return s.status(400).json({error:'Select a shop first'});data.settingsByShop[shop.id]={...(data.settingsByShop[shop.id]||baseSettings),...q.body,shopName:shop.name};write(data);s.json(data.settingsByShop[shop.id])});
app.get('/api/users',auth,(q,s)=>{let data=read();s.json(data.users.filter(u=>u.shopId===q.shopId).map(safeUser))});
app.post('/api/users',auth,(q,s)=>{let data=read(),b=q.body||{},shop=shopFor(q);if(!shop)return s.status(400).json({error:'Select a shop first'});if(!b.username||!b.password||!b.name)return s.status(400).json({error:'Name, username and password required'});if(data.users.some(u=>u.username.toLowerCase()===String(b.username).toLowerCase()))return s.status(400).json({error:'Username already exists'});let h=hash(b.password),u={id:id('USR'),name:b.name,username:b.username,role:b.role||'Staff',permissions:b.permissions||[],shopId:shop.id,...h,createdAt:new Date().toISOString()};data.users.push(u);write(data);s.status(201).json(safeUser(u))});
app.put('/api/users/:id',auth,(q,s)=>{let data=read(),u=data.users.find(x=>x.id===q.params.id);if(!u||!own(q,u))return s.status(404).json({error:'Not found'});Object.assign(u,{name:q.body.name||u.name,role:q.body.role||u.role,permissions:q.body.permissions||u.permissions});if(q.body.password){let h=hash(q.body.password);u.salt=h.salt;u.hash=h.hash}write(data);s.json(safeUser(u))});
app.delete('/api/users/:id',auth,(q,s)=>{let data=read(),u=data.users.find(x=>x.id===q.params.id);if(!u||!own(q,u))return s.status(404).json({error:'Not found'});if(u.id===q.user.id)return s.status(400).json({error:'You cannot delete your own account'});data.users=data.users.filter(x=>x.id!==u.id);write(data);s.json({ok:true})});
app.get('/api/backup',auth,(q,s)=>{let data=read(),shop=shopFor(q);if(!shop)return s.status(400).json({error:'Select a shop first'});let out={shop,settings:data.settingsByShop[shop.id],users:data.users.filter(u=>u.shopId===shop.id).map(safeUser)};for(const k of collections)out[k]=scopedRows(data,k,shop.id);s.setHeader('Content-Disposition','attachment; filename='+shop.name.replace(/[^a-z0-9]+/gi,'-').toLowerCase()+'-backup.json');s.type('json').send(JSON.stringify(out,null,2))});
app.use((q,s)=>s.sendFile(path.join(__dirname,'public','index.html')));
app.listen(PORT,'0.0.0.0',()=>console.log('SHAM MULTI-SHOP system running on port '+PORT));
